Feature/implement weighting operation
fga-eps-mds/2021-2-MeasureSoftGram-Core pull request #13
Opened 2022-03-27 19:26 UTC by anabfs

# Implementar operação de ponderação

## Descrição
Draft pull request para mostrar o que foi feito até o momento

[Implementar operação de ponderação](https://github.com/fga-eps-mds/2021-2-MeasureSoftGram-Doc/issues/60)

## Critérios de aceitação

1.[ ] Deve realizar o produto tensorial do peso definido para as caracteristicas, subcaracteristicas e medidas pela dimensão correspondente à elas
2. [ ] O tensor não pode ter uma quantidade maior de dimensões do que o definido na entrada (em todos os níveis)

2022-04-01 02:41 UTC, Rhuancpq approved these changes

2022-04-01 02:41 UTC, Rhuancpq commented on tests/unit/test_weighting.py
> +def test_diference_size():
`test_different_sizes` seria melhor não?

2022-04-01 02:44 UTC, Rhuancpq requested changes

2022-04-01 02:44 UTC, Rhuancpq commented on tests/unit/test_weighting.py
> +def test_diference_size():
`test_different_sizes` seria melhor não?

2022-04-01 21:15 UTC, igor-paiva requested changes

2022-04-01 21:15 UTC, igor-paiva commented on tests/unit/test_weighting.py
> +        assert True
Isso aqui funciona, mas não é a melhor maneira de fazer isso. Vejam os seguintes links:

- https://stackoverflow.com/questions/23337471/how-to-properly-assert-that-an-exception-gets-raised-in-pytest
- https://docs.pytest.org/en/6.2.x/assert.html#assertions-about-expected-exceptions
- https://github.com/fga-eps-mds/2021-2-MeasureSoftGram-Core/blob/develop/tests/unit/test_interpretation_functions.py

2022-04-01 21:15 UTC, igor-paiva commented on tests/unit/test_weighting.py
> +    assert pytest.approx(res.tolist()) == [0.09, 0.144, 0.03]
Comentando nesse assert, mas vale para todos que utilizarem o `pytest.approx`. Leiam [aqui](https://docs.pytest.org/en/6.2.x/reference.html#pytest-approx) sobre esse método que estão usando e vejam se o intervalo que ele considera faz sentido (a ideia é pensar mesmo e ver se precisa mudar).

2022-04-01 21:20 UTC, igor-paiva commented
Duas coisas:

- Acho que já tava certo isso, mas é bom parametrizar alguns desses testes. Para mais informações sobre tem a [documentação do pytest](https://docs.pytest.org/en/6.2.x/example/parametrize.html) e também aquele conteúdo de testes que passamos para vocês.
- Espero que vocês tenham estudado o material de testes que passamos para vocês, então reflitam sobre esses testes que vocês fizeram e se teria algum caso de teste que seria interessante adicionar

2022-04-07 22:25 UTC, igor-paiva requested changes

2022-04-07 22:25 UTC, igor-paiva commented on src/core/weighting.py
> +    else:
Acho que aqui cabe bem usar guard clause. Nesta mensagem eu explico melhor: https://discord.com/channels/938791688556666940/942765697472266251/954774023424856124.

2022-04-07 22:25 UTC, igor-paiva commented on src/core/weighting.py
> +        raise InvalidWeightSize
Pela comparação do `if` e pela docstring da classe (InvalidWeightSize) esse nome não tá fazendo 100% de sentido. Porque o erro não é exatamente a quantidade de pesos inválida e sim que ela tá divergindo com o que vem no "df".

2022-04-07 22:25 UTC, igor-paiva commented on src/core/weighting.py
> +def weighting_operation(df, weights):
O nome "df" para o parâmetro não está descritivo. E seria legal aqui uma [docstring](https://pandas.pydata.org/docs/development/contributing_docstring.html) explicando o que esse método faz (não precisa ser tão descritiva quanto o exemplo do pandas).

2022-04-07 22:25 UTC, igor-paiva commented on tests/unit/test_weighting.py
> +#     assert res == [[[0.23234132]], [[0.00202036]], [[0.30709461]]]
Código comentado desnecessário

2022-04-07 22:25 UTC, igor-paiva commented on tests/unit/test_weighting.py
> +            raise InvalidWeightingOperation
Não entendi a necessidade dessa exceção, pois a função de ponderação nem lança ela. Não seria melhor fazer um assert? Mas qual o objetivo desse teste? É testar se encontra um valor errado? Mas o caso de teste de cima já não faz isso?

2022-04-07 22:25 UTC, igor-paiva commented on tests/unit/test_weighting.py
> +    assert len(values) == len(weights)
Não entendi o objetivo deste teste, ele nem executa a função de ponderação.

2022-04-07 22:25 UTC, igor-paiva commented on tests/unit/test_weighting.py
> +            raise InvalidEqualityOfWeightAndValues
Não entendi o objetivo deste teste, ele nem executa a função de ponderação.

Trazendo do material que passamos pra vocês:

>“Testar é o processo de executar um programa com a intenção de achar erros.” (MYERS, BADGETT e SANDLER, 2012, p. 6, tradução nossa)

2022-04-07 22:38 UTC, igor-paiva requested changes

2022-04-07 22:38 UTC, igor-paiva commented on src/core/exceptions.py
> +class InvalidEqualityOfWeightAndValues(MeasureSoftGramCoreException):
A exception não precisa começar com "Invalid", vocês podem tentar descrever melhor. "Invalid Equality Of Weight And Values" fica um pouco estranho tentem pensar no que realmente significa essa exception. Que tal "ValuesAndWeightsOfDifferentSizes"?

2022-04-07 22:38 UTC, igor-paiva commented on tests/unit/test_weighting.py
> +        check = weighting_operation(values, weights)
"check" não é um nome descritivo.

Aplica aqui e em outros casos de testes também.

2022-04-08 23:19 UTC, igor-paiva requested changes

2022-04-08 23:19 UTC, igor-paiva commented on src/core/exceptions.py
> +    """Raised when the weighting operation return a invalid result"""
Essa classe não é mais utilizada

2022-04-09 00:07 UTC, igor-paiva approved these changes

2022-04-09 16:25 UTC, Rhuancpq approved these changes

2022-04-09 16:26 UTC, merged